### ISSUE TITLE
AutoUpdate.sh问题

### ISSUE THREAD

**Issue by wg1992** [281677160/common#3]
AutoUpdate.sh第435行有引号会报错，无法更新固件。
手输命令可以更新

**Comment by 281677160** [comment]
没有头绪，不明不白

**Comment by wg1992** [comment]
/usr/bin/AutoUpdate: line 435: sysupgrade -q: not found
有引号会报这个错误

**Comment by wg1992** [comment]
"${Upgrade_Options}" "${CLOUD_Version}"
这行的引号需要全部去除
