### ISSUE TITLE
打包完上传不了了

### ISSUE THREAD

**Issue by MonetND** [281677160/common#7]
[ SUCCESS ] All process completed successfully.
mv: cannot stat '/home/runner/work/build-actions/build-actions/amlogic/out/*': No such file or directory

 [OK] 固件打包完成,已将固件存入[openwrt/bin/targets/armvirt/64]文件夹内
0s
Run actions/upload-artifact@main
Warning: No files were found with the provided path: /home/runner/work/build-actions/build-actions/openwrt/bin/targets/armvirt/64. No artifacts will be uploaded.

**Comment by 281677160** [comment]
修复好了，现在应该没问题了
